### ISSUE TITLE
Flowerfeldstrasse.pal warning when loaded on the Pocket

### ISSUE THREAD

**Issue by LordRembo** [Xukkorz/openFPGA-Palettes-GalleryWebApp#1]
Nice work! I got most of them to work, except 1. When trying to load the 'Flowerfeldstrasse' palette, the Pocket says the file is too big and the limit is 56 bytes. Inspecting the file, it is 102.

**Comment by Xukkorz** [comment]
I'll fix it, I suspect github broke the rename.

**Comment by Xukkorz** [comment]
Re-Uploaded, should be correct now.
